"""
Database Models Module
======================
SQLModel database models for persisting road profiles in SQLite.

Note: This module contains database models (SQLModel with table=True).
The Pydantic validation models are in the main models.py file.
"""

import json

from sqlmodel import Field, SQLModel


class RoadProfileDB(SQLModel, table=True):
    """
    SQLModel database model for road profiles.

    This model represents a road profile stored in the SQLite database.
    Coordinates are stored as JSON-serialized strings to maintain
    compatibility with SQLite's limited type system.

    Attributes:
    -----------
    id : int | None
        Primary key, auto-generated by the database.
    name : str
        Unique name identifier for the road profile.
    x_coordinates : str
        JSON-serialized list of x-axis coordinates (floats).
    y_coordinates : str
        JSON-serialized list of y-axis coordinates (floats).
    """

    __tablename__ = "road_profiles"  # pyright: ignore[reportAssignmentType]

    id: int | None = Field(default=None, primary_key=True)
    name: str = Field(index=True, unique=True, max_length=100)
    x_coordinates: str = Field(description="JSON-serialized list of x coordinates")
    y_coordinates: str = Field(description="JSON-serialized list of y coordinates")

    def get_x_coordinates(self) -> list[float]:
        """
        Deserialize and return x_coordinates as a list of floats.

        Returns:
        --------
        list[float]
            The x-axis coordinates.
        """
        return json.loads(self.x_coordinates)

    def get_y_coordinates(self) -> list[float]:
        """
        Deserialize and return y_coordinates as a list of floats.

        Returns:
        --------
        list[float]
            The y-axis coordinates.
        """
        return json.loads(self.y_coordinates)

    @classmethod
    def from_coordinates(cls, name: str, x_coords: list[float], y_coords: list[float]) -> "RoadProfileDB":
        """
        Create a RoadProfileDB instance from coordinate lists.

        Parameters:
        -----------
        name : str
            The profile name.
        x_coords : list[float]
            The x-axis coordinates.
        y_coords : list[float]
            The y-axis coordinates.

        Returns:
        --------
        RoadProfileDB
            A new database model instance with serialized coordinates.
        """
        return cls(
            name=name,
            x_coordinates=json.dumps(x_coords),
            y_coordinates=json.dumps(y_coords),
        )
